CREATE TABLE [dbo].[ECGreenPay_LODetail] (
    [id]                       INT            IDENTITY (1, 1) NOT NULL,
    [cre_userid]               VARCHAR (50)   DEFAULT ('') NULL,
    [cre_time]                 DATETIME       DEFAULT (getdate()) NULL,
    [upd_userid]               VARCHAR (50)   DEFAULT ('') NULL,
    [upd_time]                 DATETIME       DEFAULT (getdate()) NULL,
    [customer_id]              VARCHAR (50)   DEFAULT ('') NULL,
    [order_id]                 VARCHAR (50)   DEFAULT ('') NULL,
    [MerchantID]               NVARCHAR (10)  DEFAULT ('') NULL,
    [TempLogisticsID]          VARCHAR (20)   DEFAULT ('') NULL,
    [GoodsAmount]              INT            DEFAULT ((0)) NULL,
    [IsCollection]             NVARCHAR (1)   DEFAULT ('') NULL,
    [GoodsName]                NVARCHAR (50)  DEFAULT ('') NULL,
    [SenderName]               NVARCHAR (10)  DEFAULT ('') NULL,
    [SenderZipCode]            VARCHAR (6)    DEFAULT ('') NULL,
    [SenderAddress]            NVARCHAR (60)  DEFAULT ('') NULL,
    [Remark]                   NVARCHAR (60)  DEFAULT ('') NULL,
    [ServerReplyURL]           NVARCHAR (200) DEFAULT ('') NULL,
    [ClientReplyURL]           NVARCHAR (200) DEFAULT ('') NULL,
    [Temperature]              VARCHAR (4)    DEFAULT ('') NULL,
    [Specification]            VARCHAR (4)    DEFAULT ('') NULL,
    [ScheduledPickupTime]      VARCHAR (1)    DEFAULT ('') NULL,
    [ReceiverAddress]          NVARCHAR (60)  DEFAULT ('') NULL,
    [ReceiverCellPhone]        VARCHAR (10)   DEFAULT ('') NULL,
    [ReceiverPhone]            VARCHAR (20)   DEFAULT ('') NULL,
    [ReceiverName]             NVARCHAR (10)  DEFAULT ('') NULL,
    [EnableSelectDeliveryTime] NVARCHAR (1)   DEFAULT ('') NULL,
    [EshopMemberID]            NVARCHAR (24)  DEFAULT ('') NULL,
    [LogisticsType]            NVARCHAR (20)  DEFAULT ('') NULL,
    [LogisticsSubType]         NVARCHAR (20)  DEFAULT ('') NULL,
    [ReceiverZipCode]          VARCHAR (6)    DEFAULT ('') NULL,
    [ScheduledDeliveryDate]    NVARCHAR (10)  DEFAULT ('') NULL,
    [ScheduledDeliveryTime]    VARCHAR (2)    DEFAULT ('') NULL,
    [ReceiverStoreID]          NVARCHAR (6)   DEFAULT ('') NULL,
    [ReceiverStoreName]        NVARCHAR (10)  DEFAULT ('') NULL,
    [ReturnStoreID]            VARCHAR (6)    DEFAULT ('') NULL,
    [MerchantTradeNo]          NVARCHAR (20)  DEFAULT ('') NULL,
    [LogisticsID]              VARCHAR (20)   DEFAULT ('') NULL,
    [UpdateStatusDate]         VARCHAR (20)   DEFAULT ('') NULL,
    [LogisticsStatusName]      NVARCHAR (100) DEFAULT ('') NULL,
    [LODStatus]                NVARCHAR (50)  DEFAULT ('') NULL,
    CONSTRAINT [PK_ECGreenPay_LODetail] PRIMARY KEY CLUSTERED ([id] ASC)
);

