CREATE TABLE [dbo].[ECPayGreenAIO_send] (
    [cre_userid]        VARCHAR (50)   DEFAULT ('') NULL,
    [cre_time]          DATETIME       DEFAULT (getdate()) NULL,
    [upd_userid]        VARCHAR (50)   DEFAULT ('') NULL,
    [upd_time]          DATETIME       DEFAULT (getdate()) NULL,
    [Payment_id]        INT            IDENTITY (1, 1) NOT NULL,
    [ec_order_id]       VARCHAR (50)   NULL,
    [ec_order_code]     VARCHAR (50)   NULL,
    [MerchantID]        VARCHAR (10)   DEFAULT ('') NULL,
    [MerchantTradeNo]   VARCHAR (20)   DEFAULT ('') NULL,
    [MerchantTradeDate] VARCHAR (20)   DEFAULT ('') NULL,
    [PaymentType]       VARCHAR (20)   DEFAULT ('') NULL,
    [TotalAmount]       INT            DEFAULT ((0)) NULL,
    [TradeDesc]         VARCHAR (200)  DEFAULT ('') NULL,
    [ItemName]          NVARCHAR (400) DEFAULT ('') NULL,
    [ReturnURL]         VARCHAR (200)  DEFAULT ('') NULL,
    [ChoosePayment]     VARCHAR (20)   DEFAULT ('') NULL,
    [CheckMacValue]     VARCHAR (MAX)  DEFAULT ('') NULL,
    [EncryptType]       INT            DEFAULT ((1)) NULL,
    [StoreID]           VARCHAR (10)   DEFAULT ('') NULL,
    [ClientBackURL]     VARCHAR (200)  DEFAULT ('') NULL,
    [ItemURL]           VARCHAR (200)  DEFAULT ('') NULL,
    [Remark]            VARCHAR (100)  DEFAULT ('') NULL,
    [ChooseSubPayment]  VARCHAR (20)   DEFAULT ('') NULL,
    [OrderResultURL]    VARCHAR (200)  DEFAULT ('') NULL,
    [NeedExtraPaidInfo] VARCHAR (1)    DEFAULT ('') NULL,
    [IgnorePayment]     VARCHAR (100)  DEFAULT ('') NULL,
    [PlatformID]        VARCHAR (10)   DEFAULT ('') NULL,
    [CustomField1]      NVARCHAR (50)  DEFAULT ('') NULL,
    [CustomField2]      NVARCHAR (50)  DEFAULT ('') NULL,
    [CustomField3]      NVARCHAR (50)  DEFAULT ('') NULL,
    [CustomField4]      NVARCHAR (50)  DEFAULT ('') NULL,
    [Language]          VARCHAR (3)    DEFAULT ('') NULL,
    [Redeem]            VARCHAR (1)    DEFAULT ('') NULL,
    [UnionPay]          INT            DEFAULT ((0)) NULL,
    [BindingCard]       INT            DEFAULT ((0)) NULL,
    [MerchantMemberID]  VARCHAR (30)   DEFAULT ('') NULL,
    [PeriodAmount]      INT            DEFAULT ((0)) NULL,
    [PeriodType]        VARCHAR (1)    DEFAULT ('') NULL,
    [Frequency]         INT            DEFAULT ((0)) NULL,
    [ExecTimes]         INT            DEFAULT ((0)) NULL,
    [PeriodReturnURL]   VARCHAR (200)  DEFAULT ('') NULL,
    [CreditInstallment] VARCHAR (20)   DEFAULT ('') NULL,
    [ExpireDate]        INT            DEFAULT ((0)) NULL,
    [PaymentInfoURL]    VARCHAR (200)  DEFAULT ('') NULL,
    [ClientRedirectURL] VARCHAR (200)  DEFAULT ('') NULL,
    [StoreExpireDate]   INT            DEFAULT ((0)) NULL,
    [Desc_1]            VARCHAR (20)   DEFAULT ('') NULL,
    [Desc_2]            VARCHAR (20)   DEFAULT ('') NULL,
    [Desc_3]            VARCHAR (20)   DEFAULT ('') NULL,
    [Desc_4]            VARCHAR (20)   DEFAULT ('') NULL,
    PRIMARY KEY CLUSTERED ([Payment_id] ASC)
);

