CREATE TABLE [dbo].[EinvGetWinnerList] (
    [cre_userid]      VARCHAR (255)  DEFAULT ('') NULL,
    [cre_time]        DATETIME       DEFAULT ('') NULL,
    [upd_userid]      VARCHAR (255)  DEFAULT ('') NULL,
    [upd_time]        DATETIME       DEFAULT ('') NULL,
    [winner_id]       INT            DEFAULT ('') NOT NULL,
    [tcompanyban]     VARCHAR (10)   DEFAULT ('') NULL,
    [invoiceyyymm]    VARCHAR (6)    DEFAULT ('') NULL,
    [invoiceaxle]     VARCHAR (2)    DEFAULT ('') NULL,
    [invoicenumber]   VARCHAR (8)    DEFAULT ('') NULL,
    [seller_Name]     NVARCHAR (60)  DEFAULT ('') NULL,
    [seller_Ban]      VARCHAR (10)   DEFAULT ('') NULL,
    [seller_Address]  NVARCHAR (100) DEFAULT ('') NULL,
    [invoicedate]     VARCHAR (10)   DEFAULT ('') NULL,
    [invoicetime]     VARCHAR (8)    DEFAULT ('') NULL,
    [totalamount]     VARCHAR (12)   DEFAULT ('') NULL,
    [carriertype]     VARCHAR (6)    DEFAULT ('') NULL,
    [carriername]     NVARCHAR (60)  DEFAULT ('') NULL,
    [carrierIdclear]  VARCHAR (64)   DEFAULT ('') NULL,
    [carrierIdhide]   VARCHAR (64)   DEFAULT ('') NULL,
    [randomnumber]    VARCHAR (4)    DEFAULT ('') NULL,
    [prizetype]       VARCHAR (1)    DEFAULT ('') NULL,
    [prizeamt]        VARCHAR (10)   DEFAULT ('') NULL,
    [buyer_Ban]       VARCHAR (10)   DEFAULT ('') NULL,
    [depositmk]       VARCHAR (1)    DEFAULT ('') NULL,
    [datatype]        VARCHAR (1)    DEFAULT ('') NULL,
    [except_Code]     VARCHAR (2)    DEFAULT ('') NULL,
    [except_Formate]  VARCHAR (2)    DEFAULT ('') NULL,
    [uniq_Identified] VARCHAR (24)   DEFAULT ('') NULL,
    [file_Type]       VARCHAR (1)    DEFAULT ('') NULL,
    PRIMARY KEY CLUSTERED ([winner_id] ASC)
);

