CREATE TABLE [dbo].[EinvInvoice] (
    [cre_userid]            VARCHAR (50)   DEFAULT ('') NULL,
    [cre_time]              DATETIME       DEFAULT ('') NULL,
    [upd_userid]            VARCHAR (50)   DEFAULT ('') NULL,
    [upd_time]              DATETIME       DEFAULT ('') NULL,
    [einv_id]               INT            IDENTITY (1, 1) NOT NULL,
    [ec_order_id]           VARCHAR (250)  DEFAULT ('') NULL,
    [orderID]               VARCHAR (250)  DEFAULT ('') NULL,
    [process_type]          VARCHAR (1)    DEFAULT ('') NULL,
    [sellerID]              VARCHAR (10)   DEFAULT ('') NULL,
    [buyerID]               VARCHAR (210)  DEFAULT ('') NULL,
    [buyerName]             NVARCHAR (60)  DEFAULT ('') NULL,
    [buyerAddress]          NVARCHAR (60)  DEFAULT ('') NULL,
    [mainRemark]            NVARCHAR (200) DEFAULT ('') NULL,
    [invoiceType]           VARCHAR (2)    DEFAULT ('') NULL,
    [donateMark]            VARCHAR (1)    DEFAULT ('') NULL,
    [carrierType]           VARCHAR (6)    DEFAULT ('') NULL,
    [carrierID1]            VARCHAR (64)   DEFAULT ('') NULL,
    [carrierID2]            VARCHAR (264)  DEFAULT ('') NULL,
    [printMark]             VARCHAR (1)    DEFAULT ('') NULL,
    [npoban]                NVARCHAR (10)  DEFAULT ('') NULL,
    [salesAmount]           DECIMAL (12)   DEFAULT ('') NULL,
    [freetaxSalesamount]    DECIMAL (12)   DEFAULT ('') NULL,
    [zerotaxSalesamount]    DECIMAL (12)   DEFAULT ('') NULL,
    [taxType]               VARCHAR (1)    DEFAULT ('') NULL,
    [taxrate]               DECIMAL (4, 2) DEFAULT ('') NULL,
    [taxAmount]             DECIMAL (12)   DEFAULT ('') NULL,
    [totalAmount]           DECIMAL (12)   DEFAULT ('') NULL,
    [notifyEmail]           VARCHAR (80)   DEFAULT ('') NULL,
    [customsClearanceMark]  VARCHAR (1)    DEFAULT ('') NULL,
    [unitCode]              NVARCHAR (20)  DEFAULT ('') NULL,
    [Details]               NVARCHAR (MAX) DEFAULT ('') NULL,
    [invNo]                 VARCHAR (10)   DEFAULT ('') NULL,
    [invDate]               VARCHAR (8)    DEFAULT ('') NULL,
    [invTime]               VARCHAR (8)    DEFAULT ('') NULL,
    [randomNumber]          VARCHAR (4)    DEFAULT ('') NULL,
    [invoiceCancelReason]   NVARCHAR (20)  DEFAULT ('') NULL,
    [invoiceCancelRemark]   NVARCHAR (200) DEFAULT ('') NULL,
    [invoiceCancelDate]     VARCHAR (8)    DEFAULT ('') NULL,
    [invoiceCancelTime]     VARCHAR (8)    DEFAULT ('') NULL,
    [invoiceVoidReason]     NVARCHAR (20)  DEFAULT ('') NULL,
    [invoiceVoidRemark]     NVARCHAR (200) DEFAULT ('') NULL,
    [invoiceVoidDate]       VARCHAR (8)    DEFAULT ('') NULL,
    [invoiceVoidTime]       VARCHAR (8)    DEFAULT ('') NULL,
    [salesReturnID]         VARCHAR (50)   DEFAULT ('') NULL,
    [allowanceType]         VARCHAR (1)    DEFAULT ('') NULL,
    [salesReturnDetail]     NVARCHAR (MAX) DEFAULT ('') NULL,
    [allowanceNumber]       VARCHAR (16)   DEFAULT ('') NULL,
    [allowanceDate]         VARCHAR (8)    DEFAULT ('') NULL,
    [allowanceCancelReason] NVARCHAR (20)  DEFAULT ('') NULL,
    [allowanceCancelRemark] NVARCHAR (200) DEFAULT ('') NULL,
    [allowanceCancelDate]   VARCHAR (8)    DEFAULT ('') NULL,
    [allowanceCancelTime]   VARCHAR (8)    DEFAULT ('') NULL,
    [allowanceDelete]       NVARCHAR (10)  DEFAULT ('') NULL,
    CONSTRAINT [PK_EinvInvoice] PRIMARY KEY CLUSTERED ([einv_id] ASC)
);

